let admin = new Object(); // üres objektum
let customer = {}; // üres objektum 
let user = {
    name:"Kiss Ramóna",
    age:20,
    city:"Bp",
    sayHi: function() {
        console.log("Hi");
    }

};
for (let k in user){
    console.log("Key ", k, "value ", user[k]);//keyeken megy végig
}

for(let val of Object.values(user)){
    console.log(val);
}

/*for in loops over enumerable property names of an object.

for of (new in ES6) does use an object-specific iterator and loops over the values generated by that.*/

document.getElementById("topInput");
document.getElementsByName("amount-input");
document.getElementsByClassName("form-control");

document.getElementsByTagName("h3");

let variable = document.querySelector(".form-control"); //mint a css 
document.querySelectorAll(".form-control"); //all mostanában általában csak ezeket használjuk a többi helyett
Element.prototype.setUrgent = function() { // element ősobject bővítése
    this.style.border = "solid 2px red";
}

/*let topInput = document.querySelector("input#topInput");
topInput.getAttribute("class"); //html elem attribútumai
topInput.attributes;
topInput.setAttribute("type", "email"); // html attribútum set*/

let myNodeList = document.querySelectorAll("input"); // az összes input típusú html elem módosítása
for(let i=0;i<myNodeList.length;i++){
    myNodeList[i].style.backgroundColor = "red";
}

function massModify(selector, attribute, value){
    let nodeList = document.querySelectorAll(selector);
    for( let i =0;i<NodeList.length;i++){
        nodeList[i][attribute] = value;
    }
}

topInput.childElementCount; // child elementek
document.querySelector("div.form-group:nth-child(2)").children; //form group div második gyerekének gyerekei
//.childNodes plain text elementeket is visszaadja .firstChild/ firstElementChild

let helpText = document.createElement("small");
helpText.className = "form-text text muted";
helpText.innerHTML = "Adja meg a feltéteket!";
console.log(helpText);
let parent = document.querySelector("div.form-group:nth-child(1)");
parent.appendChild(helpText);// add html element in runtime

//parent.removeChild(helpText); //remove child itemn

let sendButton = document.querySelector("form .btn.btn-primary"); 
/*sendButton.onclick = function(){ // eseménykezelő felülírja a htmlben
    alert("Hello JS!");
}*/ //meglévő methodnál nem kell (), mert azonnal lefut
sendButton.addEventListener("click", function(){ // + eventlistener
    alert("Hello JS!");
});

let orderForm = document.querySelector("#orderForm");
orderForm.addEventListener("submit",function(ev){
    ev.preventDefault();// az alap esemény blokkolása
    console.log(this);
    let inputs = this.querySelectorAll("input");
    let values = {};
    for(let i =0; i<inputs.length; i++) values[inputs[i].name]= inputs[i].value;
    console.log(values);
});
//new Date().getDay(); // 0 index, vasárnappal kezdődik 

let alerCloseButtons = document.querySelectorAll(".btn-close[data-bs-dismiss='alert']");
let alertCloseEventHandlerFunction = function(ev){
    this.parentElement.style.display = "none"; //gomb parent elementjének elrejtése
};

for(let i = 0; i<alerCloseButtons.length; i++){
    alerCloseButtons[i].addEventListener("click",alertCloseEventHandlerFunction);
        //console.log(ev);       
    };

//select elem kitöltése

let toppings= [
    "szalonna",
    "hagyma",
    "tojás",
    "paradicsom"
];
let toppingSelect = document.querySelector("#topInput");
let i =0;
    while(i<toppings.length){
        let option = document.createElement("option");
        option.value=toppings[i];
        option.innerHTML=toppings[i];
        toppingSelect.appendChild(option);
        i++;
    }


function calcAmount()
{
    let price = 1000;
    let amountInput = document.querySelector("input[name='amount-input']");
    let showAmount = document.querySelector("span.show-amount");
    let amountNumber = parseInt(amountInput.value);
    
    amountNumber = isNaN(amountNumber) ? 0 : amountNumber;
    
    
    if(amountNumber>10)
    {
        alert("Max 10 db!");
        return;
    }
    else if(amountNumber<1)
    {
        alert("Min 1 db kell!");
        return;
    }
    
    
    
    let amount = amountNumber*price;
    

    showAmount.innerHTML = amount;
}